### ISSUE TITLE
Entity cannot be found error

### ISSUE THREAD

**Issue by froxybox** [VinnyDyn/NNTags#10]
Hi there! 

Configuring the NN control using the 'Relationship Name' displays an error "The entity [relationship name' cannot be found. Specify a valid query and try again". You're able to select options, but on save/refresh, the colour disappears. 
![2021-05-21 09_35_12-Test_ Information_ test - Power Apps](https://user-images.githubusercontent.com/55729866/119063490-674ccd00-ba18-11eb-8332-d4c2a6c624af.png)

Changing it to use the 'Entity Relationship Name' displays a blank error message, but shows that selections made previously have saved. 
![2021-05-21 09_39_18-Test_ Information_ test - Power Apps](https://user-images.githubusercontent.com/55729866/119063524-7c296080-ba18-11eb-9f86-2e4fc3319788.png)

This is a great control, it'd be awesome if it could be fixed!
Thank you :)

**Comment by VinnyBasile** [comment]
Hi @froxybox, sorry for delay... the PCF needs that the "Relationship Name" and "Name" be equals.

This problem occurs when the "Relationship Name" and "Name" are different.
Make sure that these values are the same.

![image](https://user-images.githubusercontent.com/36446614/124466553-2103c100-dd6d-11eb-99f8-9e3bcfd73d44.png)

Special attention when create the Many-to-Many relationship using the new interface (make.powerapps), because the platform suggest different names.

![image](https://user-images.githubusercontent.com/36446614/124467062-b901aa80-dd6d-11eb-83e8-78a88031df91.png)

**Comment by froxybox** [comment]
Oh fantastic - just tested and that worked! Thanks for the response and info!!
